# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: biblioteca.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'biblioteca.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x62iblioteca.proto\x12\nbiblioteca\"\x07\n\x05\x45mpty\"?\n\x05Livro\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06titulo\x18\x02 \x01(\t\x12\r\n\x05\x61utor\x18\x03 \x01(\t\x12\x0b\n\x03\x61no\x18\x04 \x01(\x05\":\n\x0cLivroRequest\x12\x0e\n\x06titulo\x18\x01 \x01(\t\x12\r\n\x05\x61utor\x18\x02 \x01(\t\x12\x0b\n\x03\x61no\x18\x03 \x01(\x05\"3\n\x0eLivrosResponse\x12!\n\x06livros\x18\x01 \x03(\x0b\x32\x11.biblioteca.Livro2\xc2\x01\n\nBiblioteca\x12=\n\x0cListarLivros\x12\x11.biblioteca.Empty\x1a\x1a.biblioteca.LivrosResponse\x12=\n\x0e\x41\x64icionarLivro\x12\x18.biblioteca.LivroRequest\x1a\x11.biblioteca.Livro\x12\x36\n\x0cStreamLivros\x12\x11.biblioteca.Empty\x1a\x11.biblioteca.Livro0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'biblioteca_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=32
  _globals['_EMPTY']._serialized_end=39
  _globals['_LIVRO']._serialized_start=41
  _globals['_LIVRO']._serialized_end=104
  _globals['_LIVROREQUEST']._serialized_start=106
  _globals['_LIVROREQUEST']._serialized_end=164
  _globals['_LIVROSRESPONSE']._serialized_start=166
  _globals['_LIVROSRESPONSE']._serialized_end=217
  _globals['_BIBLIOTECA']._serialized_start=220
  _globals['_BIBLIOTECA']._serialized_end=414
# @@protoc_insertion_point(module_scope)
