# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import biblioteca_pb2 as biblioteca__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in biblioteca_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BibliotecaStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListarLivros = channel.unary_unary(
                '/biblioteca.Biblioteca/ListarLivros',
                request_serializer=biblioteca__pb2.Empty.SerializeToString,
                response_deserializer=biblioteca__pb2.LivrosResponse.FromString,
                _registered_method=True)
        self.AdicionarLivro = channel.unary_unary(
                '/biblioteca.Biblioteca/AdicionarLivro',
                request_serializer=biblioteca__pb2.LivroRequest.SerializeToString,
                response_deserializer=biblioteca__pb2.Livro.FromString,
                _registered_method=True)
        self.StreamLivros = channel.unary_stream(
                '/biblioteca.Biblioteca/StreamLivros',
                request_serializer=biblioteca__pb2.Empty.SerializeToString,
                response_deserializer=biblioteca__pb2.Livro.FromString,
                _registered_method=True)


class BibliotecaServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListarLivros(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AdicionarLivro(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamLivros(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BibliotecaServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListarLivros': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarLivros,
                    request_deserializer=biblioteca__pb2.Empty.FromString,
                    response_serializer=biblioteca__pb2.LivrosResponse.SerializeToString,
            ),
            'AdicionarLivro': grpc.unary_unary_rpc_method_handler(
                    servicer.AdicionarLivro,
                    request_deserializer=biblioteca__pb2.LivroRequest.FromString,
                    response_serializer=biblioteca__pb2.Livro.SerializeToString,
            ),
            'StreamLivros': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamLivros,
                    request_deserializer=biblioteca__pb2.Empty.FromString,
                    response_serializer=biblioteca__pb2.Livro.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'biblioteca.Biblioteca', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('biblioteca.Biblioteca', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Biblioteca(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListarLivros(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/biblioteca.Biblioteca/ListarLivros',
            biblioteca__pb2.Empty.SerializeToString,
            biblioteca__pb2.LivrosResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AdicionarLivro(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/biblioteca.Biblioteca/AdicionarLivro',
            biblioteca__pb2.LivroRequest.SerializeToString,
            biblioteca__pb2.Livro.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamLivros(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/biblioteca.Biblioteca/StreamLivros',
            biblioteca__pb2.Empty.SerializeToString,
            biblioteca__pb2.Livro.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
